server:
  port: 8200

spring:
  application:
    name: oauth2-resource

security:
  oauth2:
    client:
      clientId: myClientId
      clientSecret: iskech
      userAuthorizationUri: http://localhost:8100/oauth/authorize
      grant-type: password
      scope: webClient
      access-token-uri: http://localhost:8100/oauth/token
    resource:
      userInfoUri: http://localhost:8100/user
    authorization:
      check-token-access: http://localhost:8100/oauth/check_token

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USERNAME:admin}:${EUREKA_PASSWORD:admin}@${EUREKA_HOST:localhost}:8761/eureka
      healthcheck:
        enabled: true
  instance:
    prefer-ip-address: true
    instance-id: iskech-service-${spring.application.name}@${spring.cloud.client.ipAddress}:${server.port}
