server:
  port: 8761

spring:
  application:
    name: eureka
      
eureka:
  datacenter: iksech
  environment: Dev
  server:
    waitTimeInMsWhenSyncEmpty: 0
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${EUREKA_USERNAME:admin}:${EUREKA_PASSWORD:admin}@${EUREKA_HOST:localhost}:8761/eureka
    healthcheck:
      enabled: true
  instance:
    dashboard:    
      enabled: true
      path: /x

security:
  user:
    name: admin
    password: admin
