server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_DATABASE_NAME:security_oauth2}?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    schema: classpath:db.mysql/V1.0__user_init_table.sql
    initialization-mode: embedded

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    database: ${REDIS_DATABASE_NAME:0}
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:123456}


eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USERNAME:admin}:${EUREKA_PASSWORD:admin}@${EUREKA_HOST:localhost}:8761/eureka
      healthcheck:
        enabled: true
  instance:
    prefer-ip-address: true
    instance-id: iskech-service-${spring.application.name}@${spring.cloud.client.ipAddress}:${server.port}