server:
  port: 8100

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/security_oauth2?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    schema: classpath:db.mysql/V1.0__user_init_table.sql
    initialization-mode: always


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
